set folder1="02-PROLOGUE -- Final"
set folder2="03-ACADIA -- Final"
set folder3="04-THE BOTANICAL NETWORK -- Final"
set folder4="05-THE RAPE OF THE FORESTS--Final"
set folder5="06-SURVEYORS--Final"
set folder6="07-RIVER JOURNEYS--Final"
set folder7="08-ICE MIGRATION AND ISOLATION--Final"
set folder8="09-THE RISE OF THE NATURAL HISTORY SOCIETIES--Final"
set folder9="10-FROM INVENTORY TO ECOLOGY--Final"
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder1%/content.xml -xsl:ooxml-to-html.xsl folder=%folder1% > chapter1.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder2%/content.xml -xsl:ooxml-to-html.xsl folder=%folder2% > chapter2.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder3%/content.xml -xsl:ooxml-to-html.xsl folder=%folder3% > chapter3.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder4%/content.xml -xsl:ooxml-to-html.xsl folder=%folder4% > chapter4.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder5%/content.xml -xsl:ooxml-to-html.xsl folder=%folder5% > chapter5.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder6%/content.xml -xsl:ooxml-to-html.xsl folder=%folder6% > chapter6.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder7%/content.xml -xsl:ooxml-to-html.xsl folder=%folder7% > chapter7.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder8%/content.xml -xsl:ooxml-to-html.xsl folder=%folder8% > chapter8.xhtml
java -cp c:\saxon\saxon9he.jar net.sf.saxon.Transform -t -s:%folder9%/content.xml -xsl:ooxml-to-html.xsl folder=%folder9% > chapter9.xhtml